FROM osrf/ros:jazzy-desktop-full
LABEL authors="yhkim"

RUN apt-get update

# Install Basic Things
RUN apt install wget vim git -y
RUN apt install build-essential cmake pkg-config ninja-build -y

# Set timezone to Asia/Seoul
ENV TZ=Asia/Seoul
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get install -y tzdata

# Install Libraries for mosaic-core
RUN apt install libjsoncpp-dev libssl-dev libboost-all-dev libopencv-dev libwebsocketpp-dev libcpprest-dev libfmt-dev libprotobuf-dev uuid-dev libyaml-cpp-dev -y

ARG MOSAIC_CORE_VERSION=v1.1.2
# Install mosaic-core
RUN git clone --depth 1 --branch ${MOSAIC_CORE_VERSION} \
    https://github.com/ACSL-MOSAIC/mosaic-core.git /root/mosaic-core
WORKDIR /root/mosaic-core/third_party

RUN tar -xzvf webrtc-tarballs/webrtc-6723-x86.tar.gz

WORKDIR /root/mosaic-core
RUN mkdir build && cd build && cmake -G Ninja -DBUILD_TESTS=OFF -DBUILD_PYTHON_BINDINGS=OFF .. && ninja install

# Setting up ROS2 workspace
WORKDIR /root/ros2_ws

COPY ./ ./src

RUN /bin/bash -c "source /opt/ros/jazzy/setup.bash && colcon build --symlink-install"
RUN echo "source /opt/ros/jazzy/setup.bash" >> ~/.bashrc

RUN mkdir -p /root/rosbag
RUN mkdir -p /root/mosaic_config

RUN echo "alias run-rosbag='ros2 bag play ~/rosbag --loop'" >> ~/.bashrc

# Copy and set up entrypoint script
COPY dockerfiles/entrypoint.sh /root/entrypoint.sh
RUN chmod +x /root/entrypoint.sh

ENTRYPOINT ["/root/entrypoint.sh"]
